# Generated by Django 5.2.8 on 2025-11-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='NoteInfo',
        ),
    ]
